### ISSUE TITLE
Circular Dependencies, Uncaught ReferenceError: can't access lexical declaration 'simplifyEntities' before initialization

### ISSUE THREAD

**Issue by AlexW00** [maxlath/wikibase-sdk#117]
- wikibase-sdk version: ^9.1.0
- Environment: Firefox / Chromium latest

Error:
```
Uncaught ReferenceError: can't access lexical declaration 'simplifyEntities' before initialization
    <anonymous> http://localhost:4173/assets/propertyEditor-b00fceb9.js:1075
```
![image](https://user-images.githubusercontent.com/55558407/236636275-c2e01c8c-cd71-4d5a-9d96-536a3c307d7f.png)

Bug does not occurr in development (running `vite`), only when building for production. Project repo: https://github.com/PDA-UR/graphit-frontend/tree/dev

Building for production is done via `tsc && vite build`. Vite config:
```
// vite.config.js
export default {
	// config options
	build: {
		outDir: "dist",
		emptyOutDir: true,
		minify: false,
		sourcemap: true,
		mode: "development",
		rollupOptions: {
			input: {
				home: "./index.html",
				visTest: "./src/pages/visTest/index.html",
				propertyEditor: "src/pages/propertyEditor/index.html",
			},
		},
	},
};
```

I guess the relevant code is this part, but the error doesn't give me a line number on my end. The error occurs in the sdk.
```ts
import { WBK } from "wikibase-sdk";
import type { SparqlResults } from "wikibase-sdk";

// Dont use this class directly, use the SparqlClient class instead

export default class QueryDispatcher {
	private readonly instance = "https://graphit.ur.de";
	private readonly endpoint =
		"https://query.graphit.ur.de/proxy/wdqs/bigdata/namespace/wdq/sparql";

	private readonly wbk = WBK({
		sparqlEndpoint: this.endpoint,
		instance: this.instance,
	});

	async query(sparql: string): Promise<SparqlResults> {
		const url = this.wbk.sparqlQuery(sparql);
		const headers = {};

		const response = await fetch(url, { headers });
		const data = await response.json();
		return data;
	}
}

**Comment by AlexW00** [comment]
Just tested it with Webpack, it works fine. The error only appears when using the vite build command.

**Comment by AlexW00** [comment]
it seems to be that there's a circular dependency somewhere (parse_response.js, simplify_entity.js ...)

**Comment by AlexW00** [comment]
3 circular dependencies:
```
madge --circular src/index.ts 
✖ Found 3 circular dependencies!

1) helpers/helpers.ts > helpers/wikibase_time_to_date_object.ts
2) helpers/helpers.ts > types/options.ts > types/simplify_claims.ts > helpers/parse_claim.ts
3) helpers/simplify_entity.ts > helpers/simplify.ts
```
![g](https://user-images.githubusercontent.com/55558407/236642484-13765494-447f-4338-963e-226af4acbc46.svg)

**Comment by maxlath** [comment]
I fixed the circular dependency between `simplify_entity` and `simplify` in 2a5c61d and published that fix in v9.1.1, can you see if that resolves your problem? Other circular dependencies seem to be circular `import type`, which [apparently can be ignored](https://stackoverflow.com/a/65337891/3324977)? Any opinion on this @EdJoPaTo?

**Comment by AlexW00** [comment]
> I fixed the circular dependency between `simplify_entity` and `simplify` in [2a5c61d](https://github.com/maxlath/wikibase-sdk/commit/2a5c61d7a0bd6c9a9934c36d90c2bc04dd6eab0b) and published that fix in v9.1.1, can you see if that resolves your problem? Other circular dependencies seem to be circular `import type`, which [apparently can be ignored](https://stackoverflow.com/a/65337891/3324977)? Any opinion on this @EdJoPaTo?

Thank you, the Vite build works now.

**Comment by EdJoPaTo** [comment]
yeah, `import type` can be ignored as its only done on compile time with tsc. It won't end up in the actual running code. Guess specifying what to import explicitly rather than `import * as simplify` like it happened in 2a5c61d7a0bd6c9a9934c36d90c2bc04dd6eab0b is always a good idea so its a good solution to that in my opinion.

As its fixed now I think this Issue can be closed then?

**Comment by maxlath** [comment]
yes
