### ISSUE TITLE
Convenience module for CommonJS

### ISSUE THREAD

**Issue by larsgw** [maxlath/wikibase-sdk#131]
Now that [`wikidata-sdk`](https://www.npmjs.com/package/wikidata-sdk) is deprecated on npm, could we have a convenience module (akin to `wikibase-sdk/wikidata.org`) for the CommonJS release line? I cannot convert my libraries to ESM-only.

**Comment by EdJoPaTo** [comment]
v9 switched to ES modules which is from my personal view also the future. You should also go there in the long run. Until then v8 and the wikidata-sdk convenience module are the way to go?

But thats my own opinion. Maybe maxlath has other opinions.

**Comment by larsgw** [comment]
`wikidata-sdk` is now marked as deprecated on npm, which means people who use my packages are getting warnings (https://github.com/larsgw/citation.js/issues/230). I am also hesitant to convert to ES modules because that means all my users have to switch too, and I do not see that happening right now.

**Comment by larsgw** [comment]
(So, I will indeed continue to use v8 but I was wondering if it was possible to get a `wikibase-sdk/wikidata.org`-like export there as well.)

**Comment by maxlath** [comment]
If `wikibase-sdk@v8` works for you, that would be the recommended way indeed. You can then recreate the equivalent of wikidata-sdk with
```js
const wdk = require('wikibase-sdk')({
  instance: 'https://www.wikidata.org',
  sparqlEndpoint: 'https://query.wikidata.org/sparql'
})
```
or is there any added benefit of `wikibase-sdk/wikidata.org` export that I'm missing?

I can't look deeper into that these days, sorry, but I guess as Typescript compiles the code anyway, it could also produce a CJS build, no? It would add to the already much increased complexity of this module though, so if we can avoid it, I would indeed prefer that.

**Comment by larsgw** [comment]
> or is there any added benefit of `wikibase-sdk/wikidata.org` export that I'm missing?

Not really.

**Comment by EdJoPaTo** [comment]
> I guess as Typescript compiles the code anyway, it could also produce a CJS build, no?

TypeScript can do that but it would be vastly different from "just removing the type annotations". As its already ES module output and its closer to the input I would also stay at ES module output for simplicity.

All major runtimes and browsers support ES modules for years now (if it doesn't it's probably a security nightmare) and basically everything is migrating towards ES modules. It would be weird to return to CommonJS after already migrating to ESM with this library.

**Comment by larsgw** [comment]
> basically everything is migrating towards ES modules

Do you have statistics to back that up? Again, I don't have a problem with ES modules except that I don't want to force the users of my libraries to use them.

**Comment by EdJoPaTo** [comment]
> Do you have statistics to back that up?

No I don't have actual numbers for that. But it is what I observe. Also other pre-ESM systems get removed like Gnome 45 does with their move from GJS to ESM so its not only CommonJS that gets replaced by JavaScripts own module system.

> Again, I don't have a problem with ES modules except that I don't want to force the users of my libraries to use them.

I didn't question that. Its a good cause and the reason why I haven't migrated my own libraries so far. (But I probably should on breaking changes?)
