### ISSUE TITLE
add wikidata-sdk to cdnjs

### ISSUE THREAD

**Issue by alexan1** [maxlath/wikibase-sdk#30]
For managing client libraries I use [LibMan](https://www.stevejgordon.co.uk/library-manager-libman-visual-studio-2017)

But when I tried to add it:

```
{
      "library": "wikidata-sdk",
      "destination": "lib/wikidata"
 }
```
I got the error:

> The "wikidata-sdk" library could not be resolved by the "cdnjs" provider

Of course, I can add it manually, no problem.

I just thought you can be interested to add your library to cdnjs.

**Comment by maxlath** [comment]
hi, it seems that one can request a lib to be added to cdnjs only if the repo is above 200 stars and 800 download/month. For the download, no problem, but the repo is 66 stars short: fell welcome to start a campaign to make it increase ;)

**Comment by karx** [comment]
Here is what I tweeted, 
```
Can we get this repo cross 200 stars already, its just 33 away to be able to added to cdnjs. 
It's a #javascript sdk for #Wikidata, aka, Sleezy Omnipresent Gateway to the Largest Open Knowledge engine*! 

Yeah...., lets make it even more portable shall we?
https://github.com/maxlath/wikidata-sdk
```

A couple more tweets should do the trick I feel.
I was wondering whether I should call it _engine_ or _graph_ or just _knowledge base_ in the tweet.

**Comment by maxlath** [comment]
we passed the 200 stars \o/

**Comment by Discostu36** [comment]
But it's still not on cdnjs, is it?

**Comment by maxlath** [comment]
@Discostu36 no it's not, I just assumed someone would have made the request and closed the issue, sorry ^^ I opened a request here https://github.com/cdnjs/cdnjs/issues/13976

**Comment by karx** [comment]
Congrats all!
wikibase-sdk is on cdnjs, this issue now be closed.

I created a simple example of using `wikibase-sdk` using cdnjs, as the documentation of using the bundled version was not so available (using the `WBK` export).

You can find the example [here](https://github.com/karx/karx.github.io/tree/master/Wikidata/wikibase-sdk-example), and the hosted [Live 🐱](https://karx.github.io/Wikidata/wikibase-sdk-example) of the page. 
Open for feedback.

Internet can never have enough cats.
