### ISSUE TITLE
shortLang behavior when fetching zh-hans

### ISSUE THREAD

**Issue by lisongx** [maxlath/wikibase-sdk#63]
Thanks for making this awesome tool!

I've been run into this issue when I'm trying to query `zh-hans` (simplified chinese) as a languages options in `getEntities`.  It seems to force convert it to `zh`, what's the rational behind this? In the case of `zh`, we have many variants so each language code have return different result

reference: https://github.com/maxlath/wikibase-sdk/blob/452249b364093e389d47add3c3c7e413871eb0ce/lib/utils/utils.js#L2

Should the force lang leave as an option or better just leave to the end users to convert?

thanks!

**Comment by maxlath** [comment]
thank you for reporting, as I deal mostly with languages without `-`, I didn't see that was causing this kind of behavior >< that's now fixed in `v7.1.2`
