### ISSUE TITLE
too many claims break getEntities()

### ISSUE THREAD

**Issue by ralfhauser** [maxlath/wikibase-sdk#64]
https://www.wikidata.org/wiki/Q83835  (Swiss Federal Railways - SBB) breaks getEntities() / simplify() and returns undefined result.

Seems that there are too many "owner of" (P1830) statements (too many railway stations).

==> it should be possible to sub-specify which claims shall be returned.

(or at least which ones not)

**Comment by maxlath** [comment]
could you share the breaking piece of code? I don't really get how/what is breaking

**Comment by ralfhauser** [comment]
Sure

...
const wdk = require('wikidata-sdk');
...
// Set up caching of http requests
const http = axios.create({
  headers: { 'Cache-Control': 'no-cache' },
  // cache enabled by default
  adapter: cacheAdapterEnhancer(axios.defaults.adapter)
});
   const url = wdk.getEntities({
        ids: [qid],
        format: 'json',
        props: ['labels', 'sitelinks', 'claims']
      });
      let data = null;
      return http.get(url)
      // parse into an easier to read format
        .then(r=>{
          data = r.data;
          return wdk.simplify.entity(
            r.data.entities[qid],
            {
              keepQualifiers: true
            })
        })

**Comment by maxlath** [comment]
I tried to run your code with the only change that I commented out the adapter (not knowing what `cacheAdapterEnhancer` was), and it works fine with `Q83835`

**Comment by ralfhauser** [comment]
Thanks - 
1) is it thinkable that this normally (also with a fast fibre connection) takes normally > 1 sec and results in a comparable large return object 
2) if 1, would it be possible not to even query the "owner of" (P1830)  claims with your library ?

**Comment by ralfhauser** [comment]
Created https://phabricator.wikimedia.org/T243138

**Comment by maxlath** [comment]
1. it does return a big object. https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q83835&format=json takes around 1s to download from my connection, but unless you have a use-case that requires extreme performance, 1s isn't that awfully slow, no?
2. not from the main API. You can get more custom result by using the SPARQL Query Service, but if you want data from an entity but one property, it does look like an overkill

I think that if you can't download Q83835 and simplify it using `wdk.simplify.entity`, something is likely to be wrong in your setup

**Comment by ralfhauser** [comment]
Just saw where the problem occurs with Q83835 

 stack: TypeError: Cannot destructure property `value` of 'undefined' or 'null'.
    at Object.quantity (F:\datablue\node_modules\wikidata-sdk\lib\helpers\parse_claim.js:24:21)
    at parse (F:\datablue\node_modules\wikidata-sdk\lib\helpers\parse_claim.js:84:31)
    at simplifyClaim (F:\datablue\node_modules\wikidata-sdk\lib\helpers\simplify_claims.js:96:17)
    at propClaims.map.claim (F:\datablue\node_modules\wikidata-sdk\lib\helpers\simplify_claims.js:33:19)
    at Array.map (<anonymous>)
    at simplifyPropertyClaims (F:\datablue\node_modules\wikidata-sdk\lib\helpers\simplify_claims.js:33:6)
    at simplifyClaims (F:\datablue\node_modules\wikidata-sdk\lib\helpers\simplify_claims.js:14:24)
    at simplifyClaim (F:\datablue\node_modules\wikidata-sdk\lib\helpers\simplify_claims.js:132:28)
    at propClaims.map.claim (F:\datablue\node_modules\wikidata-sdk\lib\helpers\simplify_claims.js:33:19)
