### ISSUE TITLE
how to use the keep qualifiers option

### ISSUE THREAD

**Issue by waldenn** [maxlath/wikibase-sdk#65]
Hi, I don't quite understand how to use the "keep qualifiers" interface.

Let's say I've got this query from your docs:

```
const url = wbk.getEntities({
  ids: [ 'Q146', 'Q726' ], // these IDs contain qualifiers in Wikidata
})

fetch(url)
  .then(response => response.json())
  .then(wbk.parse.wd.entities)
  .then(entities => // do your thing with those entities data)
```

So now I've got some entities (which have qualifiers in wikidata). So how would I use the API code to show the qualifiers in this context?

`wbk.simplify.claims( entity.claims, { keepQualifiers: true })
`

I've tried calling that code on each entity, but that just returns empty items for me. I would have expected to be able to set an option to show the qualifiers for all entities using eg. the "wdk.getEntities" option object. I am probably overlooking something simple here :-)

Thanks for a great library!

**Comment by maxlath** [comment]
the problem here is that you are using `wbk.parse.wd.entities` which simplifies entities, without taking options such as `keepQualifiers`; you could instead parse the response manually, which could give something like this:
```js
const wdk = require('wikidata-sdk')

const url = wdk.getEntities({
  ids: [ 'Q146', 'Q726' ]
})

fetch(url)
  .then(response => response.json())
  .then(data => wdk.simplify.entities(data.entities, { keepQualifiers: true }))
  .then(entities => // tadaa )
```

**Comment by waldenn** [comment]
Perfect, thanks for the clarification!
