### ISSUE TITLE
Support non-default script path

### ISSUE THREAD

**Issue by lucaswerkmeister** [maxlath/wikibase-sdk#77]
Currently, the library assumes that the action API endpoint is found under `/w/api.php`, i.e. that the [script path](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:$wgScriptPath) is `/w`:

https://github.com/maxlath/wikibase-sdk/blob/d04dc7c2eaa3ce7d88a0a1164cddc75907902f70/lib/wikibase-sdk.js#L26-L30

This is not true for all wikis, and I think the library would be more universally useful if it supported other wiki setups as well. (For instance, I have several development wikis locally, with script paths `/wiki1`, `/wiki2`, etc.)

**Comment by lucaswerkmeister** [comment]
Also:

**Comment by maxlath** [comment]
solved by #78
