### ISSUE TITLE
Where are the types definitions as claimed in npm?

### ISSUE THREAD

**Issue by ogroppo** [maxlath/wikibase-sdk#80]
<img width="1212" alt="Screenshot 2021-12-15 at 14 29 02" src="https://user-images.githubusercontent.com/4820803/146204785-cab7c167-f77d-41d0-8cc9-4d98c73f5c30.png">

**Comment by EdJoPaTo** [comment]
Check out #61

tldr: v6 had them, v7 changed things and as @maxlath isn't using TypeScript he doesnt want to maintain them besides the code (which is totally understandable).

The `@types/wikidata-sdk` or wikibase-sdk is probably a good place to creates types if you need them.

**Comment by maxlath** [comment]
Closing in favor of #82
