### ISSUE TITLE
Can't resolve 'querystring'

### ISSUE THREAD

**Issue by mshd** [maxlath/wikibase-sdk#81]
error - ../../node_modules/.pnpm/wikibase-sdk@7.15.0/node_modules/wikibase-sdk/lib/utils/build_url.js:8:0
Module not found: Can't resolve 'querystring'

- wikibase-sdk version: 7.15.0
- Environment: v16.13.2

querystring is deprecated since at least since last Node LTS version 14.

Please use an alternative 

[Source](https://stackoverflow.com/questions/70640271/module-not-found-error-cant-resolve-querystring-in-users-apple-documents)

**Comment by maxlath** [comment]
patched in a46fc69, should thus be fixed in `v8.0.0`
